


type 
  WxFontEncoding* {.size: sizeof(cint), importcpp: "wxFontEncoding", 
                    header: "<wx/wx.h>".} = enum 
    wxFONTENCODING_SYSTEM = - 1, wxFONTENCODING_DEFAULT, 
    wxFONTENCODING_ISO88591, wxFONTENCODING_ISO88592, wxFONTENCODING_ISO88593, 
    wxFONTENCODING_ISO88594, wxFONTENCODING_ISO88595, wxFONTENCODING_ISO88596, 
    wxFONTENCODING_ISO88597, wxFONTENCODING_ISO88598, wxFONTENCODING_ISO88599, 
    wxFONTENCODING_ISO885910, wxFONTENCODING_ISO885911, 
    wxFONTENCODING_ISO885912, wxFONTENCODING_ISO885913, 
    wxFONTENCODING_ISO885914, wxFONTENCODING_ISO885915, 
    wxFONTENCODING_ISO8859MAX, wxFONTENCODING_KOI8, wxFONTENCODING_KOI8U, 
    wxFONTENCODING_ALTERNATIVE, wxFONTENCODING_BULGARIAN, wxFONTENCODING_CP437, 
    wxFONTENCODING_CP850, wxFONTENCODING_CP852, wxFONTENCODING_CP855, 
    wxFONTENCODING_CP866, wxFONTENCODING_CP874, wxFONTENCODING_CP932, 
    wxFONTENCODING_CP936, wxFONTENCODING_CP949, wxFONTENCODING_CP950, 
    wxFONTENCODING_CP1250, wxFONTENCODING_CP1251, wxFONTENCODING_CP1252, 
    wxFONTENCODING_CP1253, wxFONTENCODING_CP1254, wxFONTENCODING_CP1255, 
    wxFONTENCODING_CP1256, wxFONTENCODING_CP1257, wxFONTENCODING_CP1258, 
    wxFONTENCODING_CP1361, wxFONTENCODING_CP12MAX, wxFONTENCODING_UTF7, 
    wxFONTENCODING_UTF8, wxFONTENCODING_EUC_JP, wxFONTENCODING_UTF16BE, 
    wxFONTENCODING_UTF16LE, wxFONTENCODING_UTF32BE, wxFONTENCODING_UTF32LE, 
    wxFONTENCODING_MACROMAN, wxFONTENCODING_MACJAPANESE, 
    wxFONTENCODING_MACCHINESETRAD, wxFONTENCODING_MACKOREAN, 
    wxFONTENCODING_MACARABIC, wxFONTENCODING_MACHEBREW, wxFONTENCODING_MACGREEK, 
    wxFONTENCODING_MACCYRILLIC, wxFONTENCODING_MACDEVANAGARI, 
    wxFONTENCODING_MACGURMUKHI, wxFONTENCODING_MACGUJARATI, 
    wxFONTENCODING_MACORIYA, wxFONTENCODING_MACBENGALI, wxFONTENCODING_MACTAMIL, 
    wxFONTENCODING_MACTELUGU, wxFONTENCODING_MACKANNADA, 
    wxFONTENCODING_MACMALAJALAM, wxFONTENCODING_MACSINHALESE, 
    wxFONTENCODING_MACBURMESE, wxFONTENCODING_MACKHMER, wxFONTENCODING_MACTHAI, 
    wxFONTENCODING_MACLAOTIAN, wxFONTENCODING_MACGEORGIAN, 
    wxFONTENCODING_MACARMENIAN, wxFONTENCODING_MACCHINESESIMP, 
    wxFONTENCODING_MACTIBETAN, wxFONTENCODING_MACMONGOLIAN, 
    wxFONTENCODING_MACETHIOPIC, wxFONTENCODING_MACCENTRALEUR, 
    wxFONTENCODING_MACVIATNAMESE, wxFONTENCODING_MACARABICEXT, 
    wxFONTENCODING_MACSYMBOL, wxFONTENCODING_MACDINGBATS, 
    wxFONTENCODING_MACTURKISH, wxFONTENCODING_MACCROATIAN, 
    wxFONTENCODING_MACICELANDIC, wxFONTENCODING_MACROMANIAN, 
    wxFONTENCODING_MACCELTIC, wxFONTENCODING_MACGAELIC, 
    wxFONTENCODING_MACKEYBOARD, wxFONTENCODING_ISO2022JP, wxFONTENCODING_MAX

const 
  wxFONTENCODING_MACMIN = wxFONTENCODING_MACROMAN
  wxFONTENCODING_MACMAX = wxFONTENCODING_MACKEYBOARD
  wxFONTENCODING_UTF16 = wxFONTENCODING_UTF16LE
  wxFONTENCODING_UTF32 = wxFONTENCODING_UTF32LE
  wxFONTENCODING_UNICODE = wxFONTENCODING_UTF32
  wxFONTENCODING_GB2312 = wxFONTENCODING_CP936
  wxFONTENCODING_BIG5 = wxFONTENCODING_CP950
  wxFONTENCODING_SHIFT_JIS = wxFONTENCODING_CP932
  wxFONTENCODING_EUC_KR = wxFONTENCODING_CP949
  wxFONTENCODING_JOHAB = wxFONTENCODING_CP1361
  wxFONTENCODING_VIETNAMESE = wxFONTENCODING_CP1258
